# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def essential
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire', '~> 4.7'
  pod 'Nuke', '~> 7.0'

end 

target 'TMDB App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  essential

  target 'TMDB AppTests' do
    inherit! :search_paths
    
    essential

  end
end
